import Head from "next/head";
import styles from "../styles/Home.module.css";
import Navbar from "../components/Navbar/Navbar";
import CardsContainer from "../components/Cards/CardsContainer";
import { wrapper } from "../app/store";
import { GetStaticProps } from "next";
import { setProducts, Product } from "../features/Product/productSlice";

export const getStaticProps: GetStaticProps = wrapper.getStaticProps(
  (store) => async () => {
    const res = await fetch("https://fakestoreapi.com/products");

    const products: Product[] = await res.json();

    store.dispatch(setProducts(products));
    return {
      props: {
        products,
      },
    };
  }
);

export default function Home({ products }: { products: Product[] }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>eCommerce Store</title>

        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <CardsContainer products={products} />
    </div>
  );
}
